export const LOAD_VOTERS = 'LOAD_VOTERS';
export const LOADING_VOTERS = 'LOADING_VOTERS';
export const PUSH_VOTERS = 'PUSH_VOTERS';

export const LOAD_CANDIDATES = 'LOAD_CANDIDATES';
export const LOADING_CANDIDATES = 'LOADING_CANDIDATES';
export const PUSH_CANDIDATES = 'PUSH_CANDIDATES';
