export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const TOGGLE_LOADING_ADMIN = 'TOGGLE_LOADING_ADMIN';
export const AUTHENTICATE_ADMIN = 'AUTHENTICATE_ADMIN';
export const IS_ADMIN_LOGGEDIN = 'IS_ADMIN_LOGGEDIN';
